# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zstucke <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/05 16:14:02 by zstucke           #+#    #+#              #
#    Updated: 2018/11/08 22:23:15 by zstucke          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file

SRCS=main.c


all:
	gcc -Wextra -Werror -Wall $(SRCS) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)
