# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zstucke <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/05 16:14:02 by zstucke           #+#    #+#              #
#    Updated: 2018/11/06 20:52:14 by zstucke          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_advanced_do-op

SRCS=main.c operations.c general_functions.c

all:
	gcc -Wextra -Werror -Wall -o $(NAME) $(SRCS)

clean:
	/bin/rm -f $(NAME)

re: clean all
